In Java, does the finally block get executed if we insert a return statement inside the try block of a try-catch-finally?